# https://starship.rs/config/#prompt

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$hg_branch\
$container\
$docker_context\
$java\
$nodejs\
$bun\
$env_var\
$php\
$python\
$ruby\
$rust\
$terraform\
$vagrant\
$battery\
$memory_usage\
$cmd_duration\
$status\
$sudo\
$time\
$line_break\
$character\
"""

# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = false

[fill]
symbol = " "
style = "bold green"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[battery]
format = ' [Battery: $symbol$percentage]($style)'

[[battery.display]]
threshold = 20
style = 'bold bg:red'

[cmd_duration]
disabled = false
min_time = 2999                   # Only show time more than 3 seconds
format = " took [$duration](red)"
show_milliseconds = false

[container]
disabled = false

[docker_context]
disabled = true

# [status]
# style = "red"
# # symbol = "❗️"
# success_symbol = "✔"
# # format = ' [$symbol$common_meaning$signal_name$maybe_int]($style) '
# # format = ' [$common_meaning$signal_name$maybe_int]($style) ' # Note: Adding $symbol causes newline issues
# # format = '[ $symbol exit code: ($maybe_int) $status]($style)'
# format = ' [\[$maybe_int\]]($style) '
# map_symbol = true
# disabled = false

[status]
style = 'bg:blue'
symbol = '🔴 '
# success_symbol = '🟢 SUCCESS'
format = ' [\[$symbol$common_meaning$signal_name$maybe_int\]]($style)'
# map_symbol = true
disabled = false

[sudo]
disabled = true

[time]
disabled = false
format = ' [\[$time\]]($style) '
time_format = "%T"
style = "dimmed white"
# utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00"

[git_branch]
disabled = false
always_show_remote = true
symbol = "🪵 "
format = "on [$symbol$remote_name:$branch]($style) "

[git_commit]
disabled = false
only_detached = false
style = 'black dimmed'

[git_metrics]
disabled = false
added_style = 'dimmed'
deleted_style = 'dimmed'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
# format = '([\[$all_status$ahead_behind\]]($style) )'

[nodejs]
style = "bold green"
not_capable_style = "bold bg:red"
version_format = "v${major}"
format = 'using $symbol [$version]($style)'
symbol = "📦"
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts", "tsx", "jsx"]

[env_var.NODE_ENV]
style = "cyan"
format = ' NODE_ENV=[$env_value]($style)'
description = 'Node JS environment defined by NODE_ENV'

[bun]
disabled = false
symbol = "🍞 "

[env_var.AWS_PROFILE]
style = "bold yellow"
format = ' AWS_PROFILE=[$env_value]($style)'
description = 'AWS Profile'

# [aws]
# format = ' [$symbol($profile )]($style)'
# # style = 'bold blue'
# symbol = '🅰 '
# disabled = true

# [aws.profile_aliases]
# xola-ci = 'CI Profile'

[php]
format = " [$symbol($version)]($style)"

[directory]
truncation_length = 4
truncate_to_repo = false
style = "cyan"
format = "[$path]($style)[$read_only]($read_only_style) "

[username]
show_always = false
format = "[$user]($style)@"
style_user = "bold white"
disabled = false

[hostname]
ssh_only = true
trim_at = "."
format = "[$hostname]($style) in "
style = "bold white"
disabled = false

[package]
disabled = false

[memory_usage]
disabled = true
threshold = 22
style = "bold dimmed red"
symbol = "Ram: "
format = ' \($symbol[${ram_pct}]($style)\) '
